apiVersion: v1
kind: Service
metadata:
  name: vapp-service
  namespace: vapp-ns
  labels:
    app: vapp
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: flask-port
  selector:
    app: vapp
    env: prod